#!/bin/zsh

set -euC

# uni
# <meta name="go-import" content="arp242.net/uni git https://github.com/arp242/uni.git">
# <meta name="go-source" content="arp242.net/uni https://github.com/arp242/uni https://github.com/arp242/uni/tree/master/{/dir}/ https://github.com/arp242/uni/tree/master/{/dir}">
# <meta http-equiv="refresh" content="0; url=https://github.com/arp242/uni">
#
# uni/v2
# <meta name="go-import" content="arp242.net/uni/v2 git https://github.com/arp242/uni.git">
# <meta name="go-source" content="arp242.net/uni/v2 https://github.com/arp242/uni https://github.com/arp242/uni/tree/master/{/dir}/ https://github.com/arp242/uni/tree/master/{/dir}">
# <meta http-equiv="refresh" content="0; url=https://github.com/arp242/uni">

# 1. Move arp242.net go packages to zgo.at domain
# 2. And move zgoat GitHub organisation stuff to arp242.net
typeset -A pkgs=(
	acidtab          ~/code/Golib
	blackmail        ~/code/Golib
	errors           ~/code/Golib
	follow           ~/code/Golib
	gadget           ~/code/Golib
	guru             ~/code/Golib
	hubhub           ~/code/Golib
	isbot            ~/code/Golib
	json             ~/code/Golib
	ps               ~/code/Golib
	sconfig          ~/code/Golib
	termfo           ~/code/Golib
	termtext         ~/code/Golib
	tz               ~/code/Golib
	z18n             ~/code/Golib
	zcache           ~/code/Golib
	zdb              ~/code/Golib
	zhttp            ~/code/Golib
	zli              ~/code/Golib
	zlog             ~/code/Golib
	zprof            ~/code/Golib
	zstd             ~/code/Golib
	zstripe          ~/code/Golib
	zvalidate        ~/code/Golib

	zsrv             ~/code/Prog
	zcert            ~/code/Prog

	# alwayscache
	# autofox
	# border
	# cantuse
	# colorcount
	# goimport
	# goimport
	# gosodoff
	# har
	# orgstat
	# singlepage
	# uni uni/v2
	
	# goatcounter      ~/code
	# goatcounter/v2   ~/code
	# zrun             zgoat
	# ztpl             zgoat
)

for name in ${(ok)pkgs}; do
	dir=$pkgs[$name]/$name
	pkg=$(cd $dir && go list)
	repo=$(cd $dir && git remote get-url origin)
	repo="https://${${${repo##git@}%%.git}//://}"

	org=${repo:h:t}
	if [[ $org != arp242 && $org != zgoat ]]; then
		print >&2 "unexpected organisation '$org' in '$repo'; skipping"
		continue
	fi

	#repo="https://github.com/zgoat/${name%/v2}"
	#[[ ${pkg:h} = arp242.net ]] && repo="https://github.com/arp242/${name%/v2}"

	printf "%-36s  │  %-26s  │  %s\n" "$(printf '%s (%s)' $pkg $name)" ${dir//$HOME\/code/\~c} $repo
	#continue

	for p in $(cd "$dir" && go list ./...); do
		name=${p##zgo.at/}
		name=${name##arp242.net/}
		#print "     $name"
		#continue

		mkdir -p "$name"
		cat <<EOF | tee "$name.html" "$name/index.html">/dev/null
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="go-import" content="$pkg git $repo.git">
	<meta name="go-source" content="$pkg $repo $repo/tree/master/{/dir}/ $repo/tree/master/{/dir}/{file}#L{line}">
	<meta http-equiv="refresh" content="0; url=$repo">
</head>
<body>
	<p>
		This is the <code>$pkg</code> Go package.
		Its homepage is at <a href="$repo">$repo</a>.
	</p>
</body>
</html>
EOF
	done
done
